apiVersion: apps/v1
kind: Deployment
metadata:
 name: mydeploy-1
spec:
 replicas: 3
 selector: 
  matchLabels:
   app: myapp3
 template:
  metadata:  # Dictionary
    name: levelup3-pod
    labels: # Dictionary
     app: myapp3
  spec:
   containers: # list
    - name: myapp3
      image: levelupk8/k8:version2
      ports:
      - containerPort: 80
